### ISSUE TITLE
ActiveDocument Roadmap

### ISSUE THREAD

**Issue by johnnyshields** [activedocument/activedocument#1]
### Goals

- Make ActiveDocument the go-to ORM for all major-NoSQL databases.
- Fix issues and remove bloat from Mongoid legacy code.
- Make code readable/understandable. Replace module inclusion with object-oriented structures where possible.

---

### Quick Follow-ups / New Baloney Fixes

- [ ] Drop support for Ruby < 3.2 (min version 3.2) if: RUBY_VERSION < '3.2'
- [ ] Drop support for Rails < 7.2 (min version 7.2)
- [ ] https://github.com/activedocument/activedocument/commit/5376919abe72a65e41e740d653ffbba05b054975 - Review parent.children_may_have_changed implementation. why "may?"
- [ ] 211d466 - MONGOID-5890 Handle BSON::Decimal128 specially when checking for changes (#6042)
- [ ] Rationalize: - Mongoid .in --> .any_in, Mongoid .nin --> .not_in, .ne --> .not_eq
- [ ] MONGOID-5827 Allow duplicate indexes to be declared -- add a proper, full-featured in-ActiveDocument validation for this.
- [ ] Check that this is applied everywhere: ● Bash(git commit -m "Merge upstream commit c6f90737a: add test (#5911)

      Merges mongodb/mongoid@c6f90737a
      PR#5911

      Changes #not method to toggle negating state instead of always setting
      it to true. This allows double negation (.not.not) to cancel out.
      Adds tests for the #not method behavior.

### Milestones

- [ ] Replace def_delegators with delegate
- [ ] **Get rid of newly-introduced baloney**
  - [ ] Revert [insane Hash shenanigans](https://github.com/mongodb/mongoid/commit/90e17115955f62242962dd2b05950765dda95526)
  - [ ] Remove Mongoid.join_contexts, make it always true, consider renaming param
  - [ ] Change Mongoid.belongs_to_required_by_default to false
  - [ ] Get rid of Mongoid.around_callbacks_for_embeds, make it always true
  - [ ] Get rid of prevent_multiple_calls_of_embedded_callbacks, make it always true
- [ ] **Query Refactor**
  - [x] ~~Initial cleanup:~~
    - [x] https://github.com/activedocument/activedocument/issues/12
    - [x] https://github.com/activedocument/activedocument/issues/19
    - [x] https://github.com/activedocument/activedocument/issues/13
    - [x] https://github.com/activedocument/activedocument/issues/14
  - [ ] https://github.com/activedocument/activedocument/issues/15
  - Introduction of AST should fix the following:
    - [ ] MONGOID-5272 - broken_and is still very broken
    - [ ] MONGOID-5178 - or is also broken
    - [ ] Return `.none` for impossible queries such as `$in: []` , (`$and: []`, `$or: []` ?)
    - [ ] https://github.com/activedocument/activedocument/issues/17
    - [ ] Auto-intersect / union conditions for `$in` and `$nin`, etc.
    - [ ] Add `code` operator for raw javascript code (in case of mongo)
    - [ ] `$type` operator should allow symbol args e.g. `:string`, `:boolean`
  - [ ] https://github.com/activedocument/activedocument/issues/22
  - [ ] https://jira.mongodb.org/browse/MONGOID-5868

- [ ] **Refactor to use composition rather than modules/inheritance**

- [ ] **Concurrency Improvement**
    - [ ] Implement parity with ActiveRecord 7.1 async methods https://blog.saeloun.com/2023/11/21/rails-7-1-expands-active-record-async-quries/
    - [ ] Look at using Concurrent::Promises for eager loading (`includes`)
    - [ ] Investigate Ruby thread pool issues

- [ ] **Persistence Refactor**
  - [ ] [MONGOID-5609](https://jira.mongodb.org/browse/MONGOID-5609) Refactor persistence type-validation (mongoize, etc.)
     - [ ] All mongoize/demongoize/evolve methods should be extracted to type adapters.
       - [x] TypeCaster: Remove __mongoize_time__
       - [x] TypeCaster: Remove __mongoize_object_id__
       - [ ] TypeCaster: Port all mongoize/demongoize
       - [ ] TypeCaster: Port all evolve
     - [ ] Demongoizing should convert to raw values
     - [ ] Mongoizing should raise an error if cannot be converted
  - [ ] Type declaration cleanup
    - [x] MONGOID-5210 / MONGOID-5184 - Allow symbol instead of classes in `field :type` declarations.
    - [x] MONGOID-4989 - Do not deprecate Symbol type
    - [x] Remove: decimal128: BSON::Decimal128,
    - [x] Remove: warn_if_unsupported_bson_type
    - [x] Remove: UNSUPPORTED_BSON_TYPES
    - [ ] Require :type value
    - [ ] Disallow type: "Class" (remove type warning for class value)
    - [ ] Add `:big_decimal_as_string` type (alias `bigdecimal_as_string`)
    - [ ] Rename `stringified_symbol` to `:symbol_as_string` type

- [ ] **Relations Refactor**
  - [ ] Embedded relations polymorphic by default (?)
  - [ ] Merge-in embedded relations tracking gem
  - [ ] [MONGOID-4434](https://jira.mongodb.org/browse/MONGOID-4434) - Refactor relations (`belongs_to_one`, `belongs_to_many`). Ability to store foreign keys on either or both sides of any association.
  - [ ] Remove from relations: `inverse_of: nil, validate: false, autosave: false`
  - [ ] Do not eager evaluate some relation assignment actions.

- [ ] Multi-Database Support
  - [ ] Client connection
  - [ ] Rename `Clients` class to Client Mananger
  - [ ] Add `Client` class, which delegates to Adapter
  - [ ] Add DB adapters
    - [ ] MongoDB adapter
       - [ ] Querying
       - [ ] Persistence
       - [ ] Advanced methods (table mgmt, indexes, atomic operators, pluck, tally, etc.)
    - [ ] DynamoDB adapter using AWS SDK
       - [ ] Querying
       - [ ] Persistence
       - [ ] Advanced methods (table mgmt, indexes, atomic operators, pluck, tally, etc.)
    - [ ] [AWS DocumentDB](https://docs.aws.amazon.com/documentdb/latest/developerguide/functional-differences.html#functional-differences.functional-benefits) (?)
    - [ ] Google Firestore adapter
       - [ ] Querying
       - [ ] Persistence
       - [ ] Advanced methods (table mgmt, indexes, atomic operators, pluck, tally, etc.)
    - [ ] CouchDB adapter
       - [ ] Querying
       - [ ] Persistence
       - [ ] Advanced methods (table mgmt, indexes, atomic operators, pluck, tally, etc.)

- [ ] **Admin Tasks**
  - [x] Get ownership of `activedocument` gem.
  - [ ] Establish maintainers and governance board.
  - [ ] Publish documentation.
  - [ ] Release gem on Rubygems

- [ ] **Mongoid backporting & cleanup**
  - [ ] Make ActiveDocument-Mongoid shim to facilitate migration.
  - [x] Remove all deprecated methods
  - [x] Drop support for old Ruby, Rails, and MongoDB server versions.
  - [ ] Merge all Mongoid patches rejected by MongoDB
    - [ ] https://github.com/mongodb/mongoid/pull/5389 --> not sure if this is needed
  - [ ] Investigate bugs/issues marked "won't fix" by MongoDB:
    - [ ] MONGOID-5583 - ActiveStorage support for Mongoid
    - [ ] MONGOID-5393 - Investigate and fix behavior of validates_uniqueness_of :conditions option
  - [ ] Fix spec runs and failures 🏃‍♀️
    - [ ] https://github.com/tablecheck/mongoid-ultra/issues/21
    - [ ] https://github.com/tablecheck/mongoid-ultra/issues/17
    - [ ] https://github.com/tablecheck/mongoid-ultra/issues/18

- [ ] Polish that gem! 💎
  - [x] Full documentation coverage.
  - [x] Document style guide.
  - [ ] Full Rubocop compliance and coverage. 🏃‍♂️
    - [x] Layout
    - [x] Lint
    - [x] Performance
    - [ ] Style
    - [ ] Rails
    - [ ] Naming
    - [ ] Rspec
    - [ ] Other
  - [ ] Metrics cops - A+ Code Climate score
  - [ ] 99.9% test coverage
  - [ ] Remove all monkey-patching.
  - [ ] Improve major performance benchmarks by 30%+ over MongoDB Mongoid.
  - [ ] RBS support

---

- [ ] Dependency Gem Migration
  - [ ] mongoid-paperclip
  - [ ] delayed_paperclip (branch: kt-paperclip-mongoid)
  - [ ] mongoid-slug
  - [ ] mongoid-encrypted-fields
  - [ ] mongoid-observers (?)
  - [ ] delayed_job_mongoid
  - [ ] mongoid_userstamp
  - [ ] cancancan-mongoid
  - [ ] client_side_validations-mongoid
  - [ ] kaminari-mongoid
  - [ ] mongoid-history
  - [ ] mongoid_orderable
  - [ ] mongoid_paranoia
  - [ ] mongoid_rails_migrations
  - [ ] mongoid-rspec
  - [ ] mongoid_relations_dirty_tracking (merge into core)
